const data_CitiesCountries = [
  { city: "Caracas", country: "Venezuela" },
  { city: "Maracaibo", country: "Venezuela" },
  { city: "Valencia", country: "Venezuela" },
  { city: "Barquisimeto", country: "Venezuela" },
  { city: "Maracay", country: "Venezuela" },
  { city: "Ciudad Guayana", country: "Venezuela" },
  { city: "San Cristóbal", country: "Venezuela" },
  { city: "Barcelona", country: "Venezuela" },
  { city: "Maturín", country: "Venezuela" },
  { city: "Cumaná", country: "Venezuela" },
  { city: "Cabo de la Vela", country: "Venezuela" },
  { city: "Punto Fijo", country: "Venezuela" },
  { city: "La Victoria", country: "Venezuela" },
  { city: "Barinas", country: "Venezuela" },
  { city: "Puerto La Cruz", country: "Venezuela" },
  { city: "Los Teques", country: "Venezuela" },
  { city: "Guanare", country: "Venezuela" },
  { city: "Coro", country: "Venezuela" },
  { city: "Santa Teresa del Tuy", country: "Venezuela" },
  { city: "San Fernando de Apure", country: "Venezuela" },
  { city: "San Felipe", country: "Venezuela" },
  { city: "Merida", country: "Venezuela" },
  { city: "Los Rastrojos", country: "Venezuela" },
  { city: "Chivacoa", country: "Venezuela" },
  { city: "Acarigua", country: "Venezuela" },
  { city: "El Vigía", country: "Venezuela" },
  { city: "Machiques", country: "Venezuela" },
  { city: "San Juan de los Morros", country: "Venezuela" },
  { city: "Cabimas", country: "Venezuela" },
  { city: "La Grita", country: "Venezuela" },
  { city: "Anaco", country: "Venezuela" },
  { city: "Valera", country: "Venezuela" },
  { city: "Ocumare del Tuy", country: "Venezuela" },
  { city: "Tinaquillo", country: "Venezuela" },
  { city: "Carora", country: "Venezuela" },
  { city: "Calabozo", country: "Venezuela" },
  { city: "Punto Fijo", country: "Venezuela" },
  { city: "La Asunción", country: "Venezuela" },
  { city: "Ejido", country: "Venezuela" },
  { city: "La Dolorita", country: "Venezuela" },
  { city: "Porlamar", country: "Venezuela" },
  { city: "San Antonio de los Altos", country: "Venezuela" },
  { city: "Guatire", country: "Venezuela" },
  { city: "Cagua", country: "Venezuela" },
  { city: "El Tigre", country: "Venezuela" },
  { city: "Palo Negro", country: "Venezuela" },
  { city: "Zaraza", country: "Venezuela" },
  { city: "Carúpano", country: "Venezuela" },
  { city: "Trujillo", country: "Venezuela" },
  { city: "Santa Rita", country: "Venezuela" },
];

module.exports = data_CitiesCountries;
